export {
    buildCompartmentBlock,
    escapeXmlAttr,
    escapeXmlContent,
    getCompartments,
    getSessionFacts,
    replaceAllCompartmentState,
    replaceAllCompartmentStateAndBumpDepth,
    type SessionFact,
} from "./compartment-storage";
export {
    clearIndexedMessages,
    deleteIndexedMessage,
} from "./message-index";
export {
    computeProjectDocsHash,
    readProjectDocsCanonical,
} from "./project-docs-hash";
export {
    type CloneCompartmentRow,
    type CloneSessionStateFilter,
    type CloneTagRow,
    type CopySessionStateForCloneResult,
    copySessionStateForClone,
} from "./storage-clone";
export {
    applySqliteTuningPragmas,
    type ContextDatabase,
    closeDatabase,
    enforceSchemaFence,
    getDatabasePath,
    getDatabasePersistenceError,
    getPersistedSchemaVersion,
    initializeDatabase,
    isDatabasePersisted,
    LATEST_SUPPORTED_VERSION,
    type OpenDatabaseOptions,
    openDatabase,
    runSqliteOptimize,
    schemaVersionIsSupported,
    setSqlitePragmaConfig,
} from "./storage-db";
export {
    clearM0MutationsForSession,
    deleteM0Mutation,
    getM0Mutation,
    getM0MutationsAfterId,
    getM0MutationsBySession,
    getMaxM0MutationId,
    type M0MutationLogRow,
    type M0MutationType,
    queueM0Mutation,
    queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log";
export {
    getMaxMemoryMutationId,
    getMaxMemoryMutationIdForProjects,
    getMemoryMutation,
    getMemoryMutationsForRender,
    getMemoryMutationsForRenderByProjects,
    type MemoryMutationLogRow,
    type MemoryMutationType,
    queueMemoryMutation,
} from "./storage-memory-mutation-log";
export {
    type AcquireWrapupResult,
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    acquireWrapupInProgress,
    addProcessedImageStrippedIds,
    addStaleReduceStrippedIds,
    advanceToolReclaimWatermark,
    appendAutoSearchHintDecision,
    applyStrippedPlaceholderDelta,
    clearCachedM0,
    clearCachedM0M1,
    clearDeferredExecutePendingIfMatches,
    clearDetectedContextLimit,
    clearEmergencyDrainLatch,
    clearEmergencyRecovery,
    clearHistorianDrainFailure,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedReasoningWatermark,
    clearPersistedTodoSyntheticAnchor,
    clearSession,
    type DeferredExecutePayload,
    DRAIN_WINDOW_MS,
    getAutoSearchHintDecisions,
    getHistorianFailureState,
    getOrCreateSessionMeta,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedReasoningWatermark,
    getPersistedTodoSyntheticAnchor,
    getProcessedImageStrippedIds,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getSessionWorkMetrics,
    getStaleReduceStrippedIds,
    getStrippedPlaceholderIds,
    getWrapupInProgressState,
    incrementHistorianFailure,
    isWrapupInProgress,
    loadPersistedUsage,
    loadProtectedTailMeta,
    markProtectedTailPolicyV3Seeded,
    markSessionCleanupPending,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistCachedM0Payload,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    type PersistedUsageState,
    type ProtectedTailDrainReservation,
    type ProtectedTailDrainReserveResult,
    type ProtectedTailMeta,
    type ProtectedTailSeedResult,
    peekDeferredExecutePending,
    persistCachedM0,
    protectedTailWindowBudget,
    pruneAutoSearchHintDecisions,
    recordDetectedContextLimit,
    recordHistorianDrainFailure,
    recordOverflowDetected,
    recordProtectedTailNoEligibleHead,
    recordProtectedTailPublicationFloor,
    releaseWrapupInProgress,
    removeAutoSearchHintDecisionByMessageId,
    removeStrippedPlaceholderId,
    reserveProtectedTailDrainTokens,
    resetProtectedTailNoEligibleHead,
    retryPendingSessionCleanups,
    rollbackProtectedTailDrainReservation,
    setDeferredExecutePendingIfAbsent,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedReasoningWatermark,
    setPersistedTodoSyntheticAnchor,
    setSessionWorkMetrics,
    setStrippedPlaceholderIds,
    updateSessionMeta,
    updateWrapupInProgress,
    WRAPUP_IN_PROGRESS_TTL_MS,
    type WrapupInProgressState,
} from "./storage-meta";
export { bumpSessionFactsVersion } from "./storage-meta-shared";
export {
    addNote,
    deleteNote,
    dismissNote,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    updateNote,
} from "./storage-notes";
export {
    clearPendingOps,
    getPendingOps,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops";
export {
    bumpProjectMemoryEpoch,
    bumpProjectUserProfileVersion,
    deleteProjectState,
    ensureProjectState,
    GLOBAL_USER_PROFILE_PROJECT_PATH,
    getProjectState,
    type ProjectStateRow,
    setProjectState,
} from "./storage-project-state";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source";
export {
    type ActiveTagTokenAggregate,
    AGE_RECLAIM_MIN_TOKENS,
    type AgeReclaimToolTag,
    adoptFallbackTagMessageId,
    adoptPiFallbackMessageTag,
    adoptPiFallbackToolOwnerTag,
    deleteTagsByMessageId,
    deriveTagLoadFloor,
    findAdoptableFallbackTags,
    findPiFallbackToolOwnerTags,
    getActiveTagsBySession,
    getActiveTagTokenAggregate,
    getActiveTagTokenTotalsByMessage,
    getActiveToolTagsForAgeReclaim,
    getAllStatusTagTokenTotalsFlat,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getMinMessageTagNumberForRawId,
    getOldestActiveUnprotectedToolTags,
    getPersistedToolTagAccounting,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTagsForPendingOperations,
    getTopNBySize,
    getTriggerTagTokenUpperBound,
    hasPiFallbackMessageTags,
    hasPiFallbackToolOwnerTags,
    insertTag,
    type MessageTokenTotal,
    type ToolReclaimHintTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags";
export {
    bumpEpochsForWorkspaceMemberSet,
    bumpEpochsForWorkspaceMembers,
    computeWorkspaceEpochFingerprint,
    type ExpandedWorkspaceIdentitySet,
    expandWorkspaceIdentitySet,
    expandWorkspaceIdentitySetWithAliases,
    resolveStoredPathWorkspaceIdentity,
    resolveWorkspaceIdentitySet,
    sourceNameForMemory,
    storedPathBelongsToWorkspace,
    type WorkspaceIdentitySet,
} from "./workspaces";
